In [2]:
import pandas as pd

df = pd.read_csv("mmlu.csv")
df.head()

,Unnamed: 0,Question,A,B,C,D,Answer,Subject
0,0,Find the degree for the given field extension ...,0,4,2,6,B,abstract_algebra
1,1,"Let p = (1, 2, 5, 4)(2, 3) in S_5 . Find the i...",8,2,24,120,C,abstract_algebra
2,2,Find all zeros in the indicated finite field o...,0,1,"0,1","0,4",D,abstract_algebra
3,3,Statement 1 | A factor group of a non-Abelian ...,"True, True","False, False","True, False","False, True",B,abstract_algebra
4,4,Find the product of the given polynomials in t...,2x^2 + 5,6x^2 + 4x + 6,0,x^2 + 1,B,abstract_algebra

In [3]:
print(df.columns)

Index(['Unnamed: 0', 'Question', 'A', 'B', 'C', 'D', 'Answer', 'Subject'], dtype='object')

In [4]:
print(sorted(df["Subject"].unique()))

['abstract_algebra', 'anatomy', 'astronomy', 'business_ethics', 'clinical_knowledge', 'college_biology', 'college_chemistry', 'college_computer_science', 'college_mathematics', 'college_medicine', 'college_physics', 'computer_security', 'conceptual_physics', 'econometrics', 'electrical_engineering', 'elementary_mathematics', 'formal_logic', 'global_facts', 'high_school_biology', 'high_school_chemistry', 'high_school_computer_science', 'high_school_european_history', 'high_school_geography', 'high_school_government_and_politics', 'high_school_macroeconomics', 'high_school_mathematics', 'high_school_microeconomics', 'high_school_physics', 'high_school_psychology', 'high_school_statistics', 'high_school_us_history', 'high_school_world_history', 'human_aging', 'human_sexuality', 'international_law', 'jurisprudence', 'logical_fallacies', 'machine_learning', 'management', 'marketing', 'medical_genetics', 'miscellaneous', 'moral_disputes', 'moral_scenarios', 'nutrition', 'philosophy', 'prehistory', 'professional_accounting', 'professional_law', 'professional_medicine', 'professional_psychology', 'public_relations', 'security_studies', 'sociology', 'us_foreign_policy', 'virology', 'world_religions']

In [5]:
pcmb_subjects = [
    'abstract_algebra',
    'anatomy',
    'astronomy',
    'college_biology',
    'college_chemistry',
    'college_mathematics',
    'college_physics',
    'conceptual_physics',
    'elementary_mathematics',
    'high_school_biology',
    'high_school_chemistry',
    'high_school_mathematics',
    'high_school_physics',
    'medical_genetics',
    'virology'
]

df = df[df["Subject"].isin(pcmb_subjects)]

In [6]:
print("Rows after filtering:", len(df))

Rows after filtering: 2646

In [7]:
df["Subject"].value_counts()

Subject
elementary_mathematics     378
high_school_biology        310
high_school_mathematics    270
conceptual_physics         235
high_school_chemistry      203
virology                   166
astronomy                  152
high_school_physics        151
college_biology            144
anatomy                    135
college_physics            102
college_mathematics        100
college_chemistry          100
abstract_algebra           100
medical_genetics           100
Name: count, dtype: int64

In [8]:
print(df["Answer"].head())

0    B
1    C
2    D
3    B
4    B
Name: Answer, dtype: object

In [9]:
df = df.rename(columns={
    "Question": "question",
    "A": "option_A",
    "B": "option_B",
    "C": "option_C",
    "D": "option_D",
    "Answer": "answer"
})

In [10]:
df = df[
    [
        "question",
        "option_A",
        "option_B",
        "option_C",
        "option_D",
        "answer"
    ]
]

In [11]:
df = df.dropna()
df = df.drop_duplicates()

print("Rows after cleaning:", len(df))

Rows after cleaning: 2630

In [12]:
sample_size = min(2000, len(df))

df = df.sample(
    n=sample_size,
    random_state=42
)

print("Final rows:", len(df))

Final rows: 2000

In [13]:
df.to_csv("mmlu_clean.csv", index=False)

In [14]:
from google.colab import files
files.download("mmlu_clean.csv")